### ISSUE TITLE
Add mention of S3 buckets to section on shiny deployment

### ISSUE THREAD

**Issue by clmwallace** [moj-analytical-services/platform_user_guidance#47]
As discussed with @billster45 and @samtazzyman. It would be helpful to have a note on this in the step by step guidance - admins need to create a different type of bucket, add users and link bucket to shiny app. 

https://moj-analytical-services.github.io/platform_user_guidance/deploying-a-shiny-app.html#step-by-step-guide-to-deploying-an-app about

**Comment by calumabarnett** [comment]
Implemented in #69.
