### ISSUE TITLE
AUP is not for all users?

### ISSUE THREAD

**Issue by davidread** [moj-analytical-services/platform_user_guidance#85]
The Acceptable Use Policy says it is for all users of AP:
https://moj-analytical-services.github.io/platform_user_guidance/acceptable-use-policy.html#acceptable-use-policy
However I don't think it is suitable for app users. Certainly app users (beyond MoJ) don't even see the AUP in most occasions. So I think we should change the wording.

Also, maybe there are bits from the AUP relevant to app users that we should pull out into a separate doc? Or maybe we just let each app be responsible for being clear about acceptable use?

I'm flagging this for @calumabarnett @samtazzyman to ponder and bear in mind.

**Comment by samtazzyman** [comment]
It's true - the guidance is for Analytical Platform Users, as distinct from users of the apps created by Analytical Platform Users.

I think it's the responsibility of app creators to think about responsible use of their own apps (but then I would say that).

**Comment by davidread** [comment]
Cool. I've done a PR to make that clear #88
